version: "2"
services:
  app:
    build: .
    depends_on:
      - db
    environment:
      PGHOST: "db"
      PGUSER: "postgres"
    volumes:
      - ".:/app/"
    ports:
      - "3000:3000"
    tty: true
    stdin_open: true
  db:
    image: postgres
